NAME=Array
FLAGS=-Wall -Wextra -Werror
SRCS= main.cpp
HEADERS = Array.hpp

all: $(NAME)

$(NAME): $(SRCS) $(HEADERS)
	c++ $(FLAGS) $(SRCS) -o $(NAME)

clean:
	rm -rf *.o
	
fclean: clean
	rm -rf $(NAME)

re: fclean all

.PHONY: all clean fclean re